add article on writing broom tidiers
tidymodels/tidymodels.org-legacy pull request #165
Opened 2020-05-21 15:46 UTC by simonpcouch

Hi! This is a draft of an article detailing how to write `tidy()`, `glance()`, and `augment()` methods for new model objects and integrate them into the packages that export the model objects. The thought is to point folks to this when issues/PRs are filed on the broom repo to add new tidiers since, generally(?), new tidiers won’t be added to broom.

Sorry if I’ve dropped this article in the wrong directory/if any of the article metadata is weird—still getting the hang of blogdown and the website’s organization.🙂

Some other things I was thinking about while writing this up...
* The `alexpghayes/modeltests` package has unit tests for new tidiers. The tests for `augment()` methods, though, (I think) reflect a rewrite of the function that hasn’t happened yet. Is it worth linking to the tests now, or waiting until I can get to the `augment()` rewrite to write a section about writing unit tests?
* I'm not sure on how much to say about what-to-do-with/where-to-put the code once it's written. I’ve dropped an example of roxygen2 documentation and a note about dropping code in a file in the `/R` folder at the end, but maybe it’s worth writing up a quick package to demo how these tidiers would be integrated into a package. Glad to do this if it would be helpful!

2020-05-21 16:31 UTC, apreshill commented
Hi! On the blogdown side, please change the "weight" of this article in the YAML. That is what determines the order in which it shows up, and another article in this section is already assigned a weight of 2. Or switch them :) You'll need to serve the site to render the markdown version of this article so it shows up in the deploy preview link generated by Netlify.

2020-05-21 16:34 UTC, simonpcouch commented
@apreshill Ah, thanks for the pointers! On it. :-)

2020-05-21 17:36 UTC, apreshill commented
woot! https://deploy-preview-165--tidymodels-org.netlify.app/learn/develop/broom/


<img width="1035" alt="Screen Shot 2020-05-21 at 10 36 12 AM" src="https://user-images.githubusercontent.com/12160301/82587987-f944a000-9b4e-11ea-8c11-05a3e077620b.png">

2020-05-21 19:30 UTC, juliasilge commented on content/learn/develop/broom/index.markdown
> +#>  ggplot2    * 3.3.0.9000 2020-04-28 [1] Github (tidyverse/ggplot2@296eecb)
Before this is ready "for real", this will need to be rendered with only CRAN versions installed.

2020-05-21 20:00 UTC, simonpcouch commented on content/learn/develop/broom/index.markdown
> +#>  ggplot2    * 3.3.0.9000 2020-04-28 [1] Github (tidyverse/ggplot2@296eecb)
Thanks! Just reinstalled from CRAN and rebuilt.🙂

2020-05-21 21:35 UTC, topepo commented on content/learn/develop/broom/index.Rmarkdown
> +First you'll need to add the [modelgenerics](https://github.com/tidymodels/modelgenerics) package to `Imports`. We recommend using the [usethis](https://github.com/r-lib/usethis) package for this:
The package names was changed to `generics` (instead of `modelgenerics`)

2020-05-21 21:39 UTC, topepo commented on content/learn/develop/broom/index.Rmarkdown
> +The `tidy(x, ...)` method will return a tibble where each row contains information about a component of the model. The `x` input is a model object, and the `...` is an optional argument to supply add
Can you write code to download this file, read them in, then print a nice html table?

2020-05-21 21:40 UTC, topepo commented on content/learn/develop/broom/index.Rmarkdown
> +A glossary giving the currently acceptable column names outputted by `tidy()` methods can be found [here](https://github.com/alexpghayes/modeltests/blob/master/data/column_glossary.rda). As a rule of
Sane thing here; can you make a nice table of them?

2020-05-21 21:42 UTC, topepo commented on content/learn/develop/broom/index.Rmarkdown
> +`glance()` returns a one-row tibble providing model-level summarizations (e.g. goodness of fitness measures and related statistics). This is useful to check for model misspecification and to compare
and here.

2020-05-21 21:43 UTC, topepo commented on content/learn/develop/broom/index.Rmarkdown
> +`augment()` methods add columns to a dataset containing information such as fitted values, residuals or cluster assignments. All columns added to a dataset have a `.` prefix to prevent existing colum
and here

2020-05-21 21:45 UTC, topepo commented on content/learn/develop/broom/index.Rmarkdown
> +* For observations where no fitted values or summaries are available (where there's missing data, for example), return `NA`.
Can you add the bolded statement: 

> **`augment()` should always return as many rows as were in `newdata`**

2020-05-21 21:46 UTC, topepo commented on content/learn/develop/broom/index.Rmarkdown
> +#'
I would add a `@return` value since CRAN will ding you for not having one.

2020-05-21 22:11 UTC, apreshill commented on content/learn/develop/broom/index.Rmarkdown
> +* For observations where no fitted values or summaries are available (where there's missing data, for example), return `NA`.
(butting in) @simonpcouch you also have these shortcode boxes at your disposal for calling attention to things: https://github.com/tidymodels/tidymodels.org/pull/154
![81434758-b0472180-9134-11ea-860b-1a6bb47b9ae0](https://user-images.githubusercontent.com/12160301/82611425-5eab8780-9b75-11ea-88d4-a7fdaac18951.png)

2020-05-22 15:18 UTC, simonpcouch commented
Just pushed some changes!

I'm feeling unsure on the best way to present the argument / column name glossaries. I currently just link to the glossaries throughout the article and then print the tables using `kable()`, but they're _really_ long and narrow. Might be worth trying to break them up into three tables printed side by side / a wide-pivoted version of the table with a bunch of NAs in the `glance()` and `augment()` columns or adding some descriptions of each argument so the glossaries don't appear so narrow.

Open to ideas! I also could be overthinking this. Let me know. :-)

2020-05-22 20:15 UTC, topepo commented
I'm fine with the tables as-is. 

@apreshill and @juliasilge - ok to merge?

2020-05-22 20:26 UTC, juliasilge commented
I've got a round of light editing to do still. I'll take that on Monday. No, wait -- Tuesday.

2020-05-25 18:32 UTC, juliasilge requested changes
This article looks fantastic! ✨ I am really glad we are including this on tidymodels.org, and it is super clear and helpful.

2020-05-25 18:32 UTC, juliasilge commented on content/learn/develop/broom/index.Rmarkdown
> +Each of the three verbs above are _generic_, in that they do not actually define a procedure to tidy a given model object, but instead redirect to the relevant _method_ implemented to tidy a specific
```suggestion
Each of the three verbs above are _generic_, in that they do not define a procedure to tidy a given model object, but instead redirect to the relevant _method_ implemented to tidy a specific type of model object. The broom package provides tidier methods for model objects from over 100 modeling packages along with nearly all of the model objects in the stats package that comes with base R. However, for maintainability purposes, the broom package authors now ask that requests for new tidier methods be first directed to the parent package (i.e. the package that supplies the model object) rather than to broom. Tidiers will generally only be integrated into broom in the case that the requester has already asked the maintainers of the model-owning package to implement tidiers in the parent package.
```

2020-05-25 18:32 UTC, juliasilge commented on content/learn/develop/broom/index.Rmarkdown
> +As a result, we'd like to make implementing external tidier methods as painless as possible. The general process for doing so is as follows:
```suggestion
We'd like to make implementing external tidier methods as painless as possible. The general process for doing so is:
```

2020-05-25 18:32 UTC, juliasilge commented on content/learn/develop/broom/index.Rmarkdown
> +## Re-export the Tidier Generics
```suggestion
## Re-export the tidier generics
```

2020-05-25 18:32 UTC, juliasilge commented on content/learn/develop/broom/index.Rmarkdown
> +Oftentimes it doesn't make sense to define one or more of these methods for a particular model. In this case, just implement the methods that do make sense.
```suggestion
Oftentimes it doesn't make sense to define one or more of these methods for a particular model. In this case, only implement the methods that do make sense.
```

2020-05-25 18:32 UTC, juliasilge commented on content/learn/develop/broom/index.Rmarkdown
> +{{% warning %}} Please do not define `tidy()`, `glance()` or `augment()` generics in your package. This will result in namespace conflicts whenever your package is used along other packages that also
```suggestion
{{% warning %}} Please do not define `tidy()`, `glance()`, or `augment()` generics in your package. This will result in namespace conflicts whenever your package is used along other packages that also export tidying methods. {{%/ warning %}}
```

2020-05-25 18:32 UTC, juliasilge commented on content/learn/develop/broom/index.Rmarkdown
> +## Implement Tidying Methods
```suggestion
## Implement tidying methods
```

2020-05-25 18:32 UTC, juliasilge commented on content/learn/develop/broom/index.Rmarkdown
> +This output gives some summary statistics on the residuals (which would be described more fully in an `augment()` output), model coefficients (which, in this case, make up the `tidy()` output, and so
```suggestion
This output gives some summary statistics on the residuals (which would be described more fully in an `augment()` output), model coefficients (which, in this case, make up the `tidy()` output), and some model-level summarizations such as RSE, $R^2$, etc. (which make up the `glance()` output.)
```

2020-05-25 18:32 UTC, juliasilge commented on content/learn/develop/broom/index.Rmarkdown
> +### Implementing the `tidy()` Tidier
```suggestion
### Implementing the `tidy()` method
```
What do think about calling them all "method" instead of "tidier" in the headings?

2020-05-25 18:32 UTC, juliasilge commented on content/learn/develop/broom/index.Rmarkdown
> +The `tidy(x, ...)` method will return a tibble where each row contains information about a component of the model. The `x` input is a model object, and the `...` is an optional argument to supply add
```suggestion
The `tidy(x, ...)` method will return a tibble where each row contains information about a component of the model. The `x` input is a model object, and the dots (`...`) are an optional argument to supply additional information to any calls inside your method. New `tidy()` methods can take additional arguments, but _must_ include the `x` and `...` arguments to be compatible with the generic function. (For a glossary of currently acceptable additional arguments, see [the end of this article](#glossary).)  Examples of model components include regression coefficients (for regression models), clusters (for classification/clustering models), etc. These `tidy()` methods are useful for inspecting model details and creating custom model visualizations.
```

2020-05-25 18:32 UTC, juliasilge commented on content/learn/develop/broom/index.Rmarkdown
> +broom standardizes common column names used to described coefficients. In this case, the column names are:
```suggestion
The broom package standardizes common column names used to describe coefficients. In this case, the column names are:
```

2020-05-25 18:32 UTC, juliasilge commented on content/learn/develop/broom/index.Rmarkdown
> +A glossary giving the currently acceptable column names outputted by `tidy()` methods can be found [at the end of this article](#glossary)). As a rule of thumb, column names resulting from `tidy()` m
```suggestion
A glossary giving the currently acceptable column names outputted by `tidy()` methods can be found [at the end of this article](#glossary). As a rule of thumb, column names resulting from `tidy()` methods should be all lowercase and contain only alphanumerics or periods (though there are plenty of exceptions).
```

2020-05-25 18:32 UTC, juliasilge commented on content/learn/develop/broom/index.Rmarkdown
> +With this method exported, then, if a user called `tidy(fit)`, where `fit` was an output from `lm()`, the `tidy()` generic would "redirect" the call to the `tidy.lm()` function above.
```suggestion
With this method exported, then, if a user calls `tidy(fit)`, where `fit` is an output from `lm()`, the `tidy()` generic would "redirect" the call to the `tidy.lm()` function above.
```

2020-05-25 18:32 UTC, juliasilge commented on content/learn/develop/broom/index.Rmarkdown
> +* Sometimes a model will have several different types of components. For example, in mixed models, there is different information associated with fixed effects and random effects, since this informat
```suggestion
* Sometimes a model will have several different types of components. For example, in mixed models, there is different information associated with fixed effects and random effects. Since this information doesn't have the same interpretation, it doesn't make sense to summarize the fixed and random effects in the same table. In cases like this you should add an argument that allows the user to specify which type of information they want. For example, you might implement an interface along the lines of:
```

2020-05-25 18:32 UTC, juliasilge commented on content/learn/develop/broom/index.Rmarkdown
> +### Implementing the `glance()` Tidier
```suggestion
### Implementing the `glance()` method
```

2020-05-25 18:32 UTC, juliasilge commented on content/learn/develop/broom/index.Rmarkdown
> +* Output should not include the name of the modeling function or any arguments given to the modelling function.
```suggestion
* Output should not include the name of the modeling function or any arguments given to the modeling function.
```

2020-05-25 18:32 UTC, juliasilge commented on content/learn/develop/broom/index.Rmarkdown
> +* `glance` should always return the same columns in the same order when given an object of a given model class. If a summary metric (such as `AIC`) is not defined in certain circumstances, use `NA`.
```suggestion
* The `glance` method should always return the same columns in the same order when given an object of a given model class. If a summary metric (such as `AIC`) is not defined in certain circumstances, use `NA`.
```

2020-05-25 18:32 UTC, juliasilge commented on content/learn/develop/broom/index.Rmarkdown
> +### Implementing the `augment()` Tidier
```suggestion
### Implementing the `augment()` method
```

2020-05-25 18:32 UTC, juliasilge commented on content/learn/develop/broom/index.Rmarkdown
> +`augment()` methods add columns to a dataset containing information such as fitted values, residuals or cluster assignments. All columns added to a dataset have a `.` prefix to prevent existing colum
```suggestion
The `augment()` methods add columns to a dataset containing information such as fitted values, residuals, or cluster assignments. All columns added to a dataset have a `.` prefix to prevent existing columns from being overwritten. (Currently acceptable column names are given in [the glossary](#glossary).) The `x` and `...` arguments share their meaning with the two functions described above. All `augment()` methods also optionally accept a `data` argument that is a `data.frame` (or `tibble`) to add observation-level information to, returning a `tibble` object with the same number of rows as `data`. Many `augment()` methods also accept a `newdata` argument, following the same conventions as the `data` argument, except with the underlying assumption that the model has not "seen" the data yet. As a result, `newdata` arguments need not contain the response columns in `data`. Only one of `data` or `newdata` should be supplied. A full glossary of acceptable arguments to `augment()` methods can be found at [the end of this article](#glossary).
```
`newdata` and `data` are arguments, not functions, so don't use parenthesis

2020-05-25 18:32 UTC, juliasilge commented on content/learn/develop/broom/index.Rmarkdown
> +If a `data` argument is not specified, `augment` should try to reconstruct the original data as much as possible from the model object. This may not always be possible, and often it will not be possi
```suggestion
If a `data` argument is not specified, `augment()` should try to reconstruct the original data as much as possible from the model object. This may not always be possible, and often it will not be possible to recover columns not used by the model.
```

2020-05-25 18:32 UTC, juliasilge commented on content/learn/develop/broom/index.Rmarkdown
> +* The `newdata` argument should default to `NULL`. Users should only ever specify one of `data` or `newdata`. Providing both `data` and `newdata` should result in an error. `newdata` should accept bo
```suggestion
* The `newdata` argument should default to `NULL`. Users should only ever specify one of `data` or `newdata`. Providing both `data` and `newdata` should result in an error. The `newdata` argument should accept both `data.frame`s and `tibble`s.
```

2020-05-25 18:32 UTC, juliasilge commented on content/learn/develop/broom/index.Rmarkdown
> +* *`augment()` should always return as many rows as were in `data` or `newdata`*, depending on which is supplied
```suggestion
* *The `augment()` method should always return as many rows as were in `data` or `newdata`*, depending on which is supplied
```

2020-05-25 18:32 UTC, juliasilge commented on content/learn/develop/broom/index.Rmarkdown
> +The only remaining step is to integrate the new tidiers into the parent package! To do so, just drop the tidiers into a `.R` file inside of the $/R$ folder and document them using roxygen2. If you're
```suggestion
The only remaining step is to integrate the new tidiers into the parent package! To do so, just drop the tidiers into a `.R` file inside of the `/R` folder and document them using roxygen2. If you're unfamiliar with the process of documenting objects, you can read more about it [here](http://r-pkgs.had.co.nz/man.html). Here's an example of how our `tidy.lm()` method might be documented:
```
Code not math

2020-05-25 18:32 UTC, juliasilge commented on content/learn/develop/broom/index.Rmarkdown
> +Once you've documented each of your new tidiers and ran `devtools::document()`, you're done! Congrats on implementing your own broom tidiers for a new model object!
```suggestion
Once you've documented each of your new tidiers and executed `devtools::document()`, you're done! Congrats on implementing your own broom tidiers for a new model object!
```

2020-05-25 19:03 UTC, simonpcouch commented
Thank you so much @juliasilge!🌺 Just pushed all changes besides the tidiers -> methods switch of language—I'm all for it if others are on board as well.

2020-05-25 19:19 UTC, juliasilge commented
We do prefer to use backticks like `newdata` for arguments. You can check out general guidelines here at the [tidyverse style guide](https://style.tidyverse.org/documentation.html#r-code).

2020-05-25 19:26 UTC, simonpcouch commented
Oh, oops—I misinterpreted your comment. Rolling back!

2020-05-26 17:48 UTC, simonpcouch commented
Went ahead and made the language switch!🙂

2020-05-26 17:52 UTC, juliasilge approved these changes

2020-05-26 17:53 UTC, juliasilge commented
I'm ready for this to merge. Anybody else want to review? 🤔

2020-05-26 18:38 UTC, topepo commented
Ship it!

2020-05-26 18:40 UTC, merged

2020-05-26 18:55 UTC, juliasilge commented
Oh man, I just noticed that the session info has dev versions. 😩 @simonpcouch Either you or I needs to open a new PR and re-render this article only with just CRAN versions. Are you able to do it or should I?

2020-05-26 19:17 UTC, simonpcouch commented
😣 Oopsies. On it!