Custom recipe step
tidymodels/tidymodels.org-legacy pull request #212
Opened 2021-02-22 16:30 UTC by hfrick

Some small changes to further increase readability - feel free to pick and choose!

I ran `blogdown::serve_site()` but the corresponding `index.markdown` file didn't change - is that what is supposed to happen?

2021-02-23 16:16 UTC, juliasilge requested changes
These are some good changes; it's been a while since we looked in detail at this article. 👍

2021-02-23 16:16 UTC, juliasilge commented on content/learn/develop/recipes/index.Rmarkdown
> +We will use the `stats::quantile()` to compute the grid. However, we might also want to have control over the granularity of this grid, so the `options` argument will be used to define how that calcu
```suggestion
We will use `stats::quantile()` to compute the grid. However, we might also want to have control over the granularity of this grid, so the `options` argument will be used to define how that calculation is done. We could use the ellipses (aka `...`) so that any options passed to `step_percentile()` that are not one of its arguments will then be passed to `stats::quantile()`. However, we recommend making a separate list object with the options and use these inside the function because `...` is already used to define the variable selection. 
```

2021-02-23 16:16 UTC, juliasilge commented on content/learn/develop/recipes/index.Rmarkdown
> +If you don't add a print method for `step_percentile`, it will still print but it will be printed as a list of (potentially large) objects and look a bit ugly. The recipes package contains a helper f
```suggestion
If you don't add a print method for `step_percentile`, it will still print but it will be printed as a list of (potentially large) objects and look a bit ugly. The recipes package contains a helper function called `printer()` that should be useful in most cases. We are using it here for the custom print method for `step_percentile`. It requires that the names of the selected columns that are resolved after `prep()` have been evaluated as well as the original terms specification. For the former, our step object is structured so that the list object `ref_dist` has the names of the selected variables: 
```
That's correct, right? "have been evaluated"? Or is there a better way to say this?

2021-02-23 16:17 UTC, juliasilge commented
The `index.markdown` _is_ supposed to change. I'd make sure you have blogdown "running" i.e. you have the server going and then make a change to the `.Rmarkdown`.

2021-02-23 17:22 UTC, hfrick commented on content/learn/develop/recipes/index.Rmarkdown
> +If you don't add a print method for `step_percentile`, it will still print but it will be printed as a list of (potentially large) objects and look a bit ugly. The recipes package contains a helper f
I think "have been evaluated" is good but the current sentence doesn't capture that the `printer()` functions needs two things: the terms specification (i.e. before `prep()`) and the actual column names (= what that specification is evaluated to by `prep()`, i.e. "after `prep()`). So maybe
> It requires the original terms specification as well as the column names this specification is evaluated to by `prep()`.
makes it clearer?

2021-02-23 18:59 UTC, hfrick commented
sooo, I got the rendered files now and added them. if you think that the sentence around terms specification evaluated to column names in `prep()` is working, then I'd say this is ready.

2021-02-23 20:33 UTC, apreshill commented
Hi- poking in to say that this line:
https://github.com/tidymodels/tidymodels.org/blob/4cf73da26ecf101da705652adfc7fbf401678bd4/.Rprofile#L17

Is why `.Rmarkdown` isn't knitting automatically when you serve site- if you knit, the local preview may take a few seconds to update.

2021-02-23 20:52 UTC, juliasilge commented
This is looking good! Just a couple more things:

- Looks like we are not using svglite for rendering the images, which we probably should be. The ones that are checked in here look different/fuzzier than the older versions so we should either switch over to svglite in `opts_chunk` or just leave out the images for now, since they did not change substantitvely.
- We should change this: "Towards the end of 2020". I know we made a [big change for tidyselect support](https://github.com/tidymodels/recipes/pull/595) in Nov 2020 but how much of this specifically changed?

2021-03-03 15:29 UTC, hfrick commented
I've left the figures out of this PR and instead added a new issue #213

2021-03-03 18:01 UTC, juliasilge commented on content/learn/develop/recipes/index.markdown
> +#>  parsnip    * 0.1.5.9000 2021-03-02 [1] local
Looks like a non-CRAN version slipped in here 👻

2021-03-03 18:37 UTC, hfrick commented on content/learn/develop/recipes/index.markdown
> +#>  parsnip    * 0.1.5.9000 2021-03-02 [1] local
:eyes:  fixed it!

2021-03-03 18:47 UTC, juliasilge approved these changes
Good to go! 🤠

2021-03-04 11:51 UTC, merged